---
title: "fine_data_2016.Rmd"
author: "Hamaad Mehal"
date: "5/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(gt)
library(ggplot2)
library(janitor)
library(devtools)
library(rvest)
library(haven)
library(magrittr)
library(infer)
```

```{r, include = FALSE}
#Address of the login webpage
login2016<-"https://www.spotrac.com/signin/?redirect=nba/fines-suspensions/2015"

#create a web session with the desired login address
pgsession2016<-html_session(login2016)
pgform2016<-html_form(pgsession2016)[[3]]  #in this case the submit is the 2nd form
filled_form2016<-set_values(pgform2016, email="hamaadmehal@college.harvard.edu", password="Brady123")
submit_form(pgsession2016, filled_form2016)

#pre allocate the final results dataframe.
results2016<-data.frame()  



#base address of the pages to extract information from
url2016<-"https://www.spotrac.com/nba/fines-suspensions/2015/"
url2016<-paste0(url2016)
page2016<-jump_to(pgsession2016, url2016)
h2016 <- read_html(page2016)
class(h2016)
h2016
html_text(h2016)
tab2016 <- h2016 %>% html_nodes("table") %>%
.[[1]] %>%
html_table() %>%
slice(1:830)
tab2016

```

```{r, include = FALSE}
count_fine_2016 <- tab2016 %>%
  select(Player) %>%
  mutate(Player = as_factor(Player)) %>% 
  count(Player) %>%
  arrange(desc(n)) %>%
  mutate(rank = rank(-n)) %>%
  slice(1:830) 

count_fine_2016 <- count_fine_2016 %>%
    mutate(Player=str_replace_all(Player, "รถ", "o")) %>%
    mutate(Player =str_replace_all(Player,"[:punct:]", ""))
```

```{r, include=FALSE}
amount_fine_2016 <- tab2016 %>%
  mutate(Amount = parse_number(Amount, na = c("", "NA"), locale = default_locale(),
  trim_ws = TRUE)) %>%
  group_by(Player) %>%
  summarise(Amount = sum(Amount)) %>%
  arrange(desc(Amount))
```

```{r, echo = FALSE}
ggplot(count_fine_2016, aes(x = Player, y = n, color = n)) +
  geom_col() +
  xlab(label = "Players") +
  ylab(label = "Number of Fines") +
  labs(title = "Number of Fines Per NBA Player in 2015-2016") +
  theme(axis.text.x=element_blank(), axis.ticks.x=element_blank())

ggsave("fp_ms_6_shiny/count_fine_2016.png", width = 10, height = 10)
```