---
title: "Join.Rmd"
author: "Hamaad Mehal"
date: "5/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(haven)
library(tidyverse)
library(janitor)
library(ggplot2)
library(tidycensus)
library(gt)
library(magrittr)
library(infer)
library(skimr)
library(tidyr)
library(broom)
library(webshot)
```

```{r}
joined_salary_fine <- full_join(count_fine, tabs, by = "fixedName")



joined_salary_fine <- joined_salary_fine %>%
  mutate(Salary = parse_number(X3, na = c("", "NA"), locale = default_locale(),
  trim_ws = TRUE)) 

joined_salary_fine

regression_model <- lm(n ~ Salary, data = joined_salary_fine) 


ggplot(joined_salary_fine, aes(Salary, n)) +
  geom_point() +
  labs(x = "Salary",
       y = "Number of Times Fined",
       title = "Relationship Between Salary and # of Times Fined") +
  geom_smooth(method='lm') +
  theme_classic()

ggsave("fp_ms_6_shiny/rel_graphs/scr2020.png", width = 10, height = 10)

regression_model %>%
  tidy(conf.int = TRUE) %>%
  select(term, estimate, conf.low, conf.high) %>%
  gt() %>%
  tab_header(title = "Effect of Salary on Number of Fines") %>%
  tab_spanner(label = "Data from Spotrac and Hoopshype", columns = 
                c("term", "estimate", "conf.low", "conf.high")) %>%
  cols_label(term = "Variable", estimate = "Estimate", conf.low =
               "Lower Bound", conf.high = "Upper Bound") 
```


```{r}
joined_salary_amount <- full_join(amount_fine, tabs, by = "fixedName")

joined_salary_amount <- joined_salary_amount %>%
  mutate(Salary = parse_number(X3, na = c("", "NA"), locale = default_locale(),
  trim_ws = TRUE))

joined_salary_amount

regression_model <- lm(Amount ~ Salary, data = joined_salary_amount) 


ggplot(joined_salary_amount, aes(Salary, Amount)) +
  geom_point() +
  labs(x = "Salary",
       y = "Total Amount of Fines",
       title = "Relationship Between Salary and Total Sum Fined") +
  geom_smooth(method='lm') +
  theme_classic()

ggsave("fp_ms_6_shiny/rel_graphs/sar2020.png", width = 10, height = 10)

regression_model %>%
  tidy(conf.int = TRUE) %>%
  select(term, estimate, conf.low, conf.high) %>%
  gt() %>%
  tab_header(title = "Effect of Salary on Total Amount of Fines") %>%
  tab_spanner(label = "Data from Spotrac and Hoopshype", columns = 
                c("term", "estimate", "conf.low", "conf.high")) %>%
  cols_label(term = "Variable", estimate = "Estimate", conf.low =
               "Lower Bound", conf.high = "Upper Bound") 

```

```{r}
joined_minute_count <- full_join(count_fine, total_minute_count_2020, by = "fixedName")

regression_model <- lm(n ~ Minutes, data = joined_minute_count) 

ggplot(joined_minute_count, aes(Minutes, n)) +
  geom_point() +
  labs(x = "Minutes",
       y = "Number of Times Fined",
       title = "Relationship Between Salary and # of Times Fined") +
  geom_smooth(method='lm') +
  theme_classic()

ggsave("fp_ms_6_shiny/rel_graphs/mcr2020.png", width = 10, height = 10)

regression_model %>%
  tidy(conf.int = TRUE) %>%
  select(term, estimate, conf.low, conf.high) %>%
  gt() %>%
  tab_header(title = "Effect of Total Minutes Played on Number of Fines") %>%
  tab_spanner(label = "Data from Spotrac and teamrankings.com", columns = 
                c("term", "estimate", "conf.low", "conf.high")) %>%
  cols_label(term = "Variable", estimate = "Estimate", conf.low =
               "Lower Bound", conf.high = "Upper Bound") 
```

```{r}
joined_minute_amount <- full_join(amount_fine, total_minute_count_2020, by = "fixedName")

regression_model <- lm(Amount ~ Minutes, data = joined_minute_amount) 

ggplot(joined_minute_amount, aes(Minutes, Amount)) +
  geom_point() +
  labs(x = "Minutes",
       y = "Total Amount of Fines",
       title = "Relationship Between Salary and Total Sum Fined") +
  geom_smooth(method='lm') +
  theme_classic() +
  ylim(0, 100000)

ggsave("fp_ms_6_shiny/rel_graphs/mar2020.png", width = 10, height = 10)

regression_model %>%
  tidy(conf.int = TRUE) %>%
  select(term, estimate, conf.low, conf.high) %>%
  gt() %>%
  tab_header(title = "Effect of Minutes on Total Amount of Fines") %>%
  tab_spanner(label = "Data from Spotrac and teamrankings.com", columns = 
                c("term", "estimate", "conf.low", "conf.high")) %>%
  cols_label(term = "Variable", estimate = "Estimate", conf.low =
               "Lower Bound", conf.high = "Upper Bound") 
```