---
title: "salary_data_2016.Rmd"
author: "Hamaad Mehal"
date: "5/11/2020"
output: html_document
---

The code for this is identical to that of Join_2020. This is just for 2019 data.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(gt)
library(ggplot2)
library(janitor)
library(devtools)
library(rvest)
library(haven)
library(magrittr)
library(infer)
```

```{r, include = FALSE}
urls2016 <- paste0("https://hoopshype.com/salaries/players/2015-2016//") 
hs2016 <- read_html(urls2016)
class(hs2016)
hs2016
html_text(hs2016)
tabs2016 <- hs2016 %>% html_nodes("table") %>%
.[[1]] %>%
html_table() %>%
slice(2:520)
tabs2016


tabs2016 <- tabs2016 %>%
  rename(fixedName = X2)
```



```{r}


salaryNames2016 <- paste(c(tabs2016$fixedName), collapse = "|")

str_replace_all(salaryNames, "รถ", "o")
str_replace_all(salaryNames, "Dennis Schroeder", "Dennis Schroder")
str_replace_all(salaryNames,"[:punct:]","")


count_fine_2016 <- count_fine_2016 %>%
  mutate(fixedName = str_extract(Player, salaryNames2016))

amount_fine_2016 <- amount_fine_2016 %>%
  mutate(fixedName = str_extract(Player, salaryNames2016))
```