---
title: "salary_data"
author: "Hamaad Mehal"
date: "4/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(gt)
library(ggplot2)
library(janitor)
library(devtools)
library(rvest)
library(haven)
library(magrittr)
library(infer)
```

```{r, include = FALSE}
urls <- paste0("https://hoopshype.com/salaries/players/") 
hs <- read_html(urls)
class(hs)
hs
html_text(hs)
tabs <- hs %>% html_nodes("table") %>%
.[[1]] %>%
html_table() %>%
slice(2:576)
tabs

# Used code from PS3 and 4 for webscrapping to pull data from tables on websites.
# Renamed values for joining and creating graphs/tables more easily.


tabs <- tabs %>%
  rename(fixedName = X2)
```

```{r, echo = FALSE}
ggplot(tabs, aes(x = fixedName, y = X3)) +
  geom_point() +
  xlab(label = "Players") +
  ylab(label = "Salary") +
  labs(title = "NBA Player's Salary in 2019-2020") +
  theme(axis.text.x=element_blank(), axis.ticks.x=element_blank())

ggsave("fp_ms_6_shiny/salary_data_2020.png", width = 10, height = 10)
```


```{r}


salaryNames <- paste(c(tabs$fixedName), collapse = "|")

# Reformatted names for the fine data to make it easier to join the data.

str_replace_all(salaryNames, "รถ", "o")
str_replace_all(salaryNames, "Dennis Schroeder", "Dennis Schroder")
str_replace_all(salaryNames,"[:punct:]","")


count_fine <- count_fine %>%
  mutate(fixedName = str_extract(Player, salaryNames))

# Created fixed name columns for these datasets to enable easy joins.

amount_fine <- amount_fine %>%
  mutate(fixedName = str_extract(Player, salaryNames))
```